Todo-List
evabanegacom/Todo-List pull request #1
Opened 2020-08-28 17:28 UTC by evabanegacom

This is a JavaScript web app 
The concept here is a todo-list using document object model to write HTML and css
We made the interface
Added the logic and functionality
Included active storage

2020-08-28 18:32 UTC, wathigo requested changes
### Changes Required.
Great job guys :clap: 
The data has been made persistent across sessions using local storage.
Let's make some changes in order to meet all the requirements.

**REQUIRED**
*  DOM-Manipulation and Logic are in separate modules ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/modules_requirement.png) from Odin). Currently, logic related code has not been separated with DOM manipulative code.
* There is a 'default' project. Let's add a default list in the local storage.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/projects_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list)).
* Let's make sure that a todo item is an object which is dynamically generated using a factory or a constructor. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/todo_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list)).

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathgo.**

2020-08-28 21:27 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far! 🙌 Kindly fix the requirement of the previous reviewer before submitting for another CRR. 🥺 

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-08-31 10:16 UTC, BrittanyBlake commented
Thank you for the review.  
We have implemented the changes requested however, in our original code, we already had the todo item as an object. If you check lines 29-37 of our list.js file, you can see the object and if you check lines 5-13 of our todos.js, you can see the class constructor. We look forward to your comments.

2020-08-31 10:50 UTC, rOluochKe requested changes
Hello Team
### You have done well so far :clap: However, you have a few issues to fix before the project can be approved.
- [ ] Add edit feature on the to do items
- [ ] Fix the linting errors raised on the pull request
- [ ] Separate app logic from dom manipulation
### Make these changes and submit for another code review. Good luck.
- Happy hacking!

By Raymond
Slack @iamraymond

2020-08-31 10:51 UTC, rOluochKe commented on src/js/list.js
> +  }
### separate app logic from dom manipulation

2020-08-31 14:10 UTC, closed without merging